// Deterministic topic labels, not a translation or an AI claim.
const consonants=['k','kh','g','gh','ng','ch','chh','j','jh','ny','t','th','d','dh','n','t','th','d','dh','n','p','ph','b','bh','m','y','r','l','v','sh','sh','s','h'];
const scripts=[0x0900,0x0a00,0x0a80,0x0b00,0x0b80,0x0c00,0x0c80,0x0d00];
const vowels={5:'a',6:'aa',7:'i',8:'ii',9:'u',10:'uu',11:'ri',15:'e',16:'ai',19:'o',20:'au'};
const marks={62:'aa',63:'i',64:'ii',65:'u',66:'uu',67:'ri',70:'e',71:'e',72:'ai',74:'o',75:'o',76:'au',77:'',1:'n',2:'m',3:'h'};
export function transliterate(value){return [...value].map(c=>{const cp=c.codePointAt(0),base=scripts.find(b=>cp>=b&&cp<b+128);if(base===undefined)return c;const n=cp-base;if(n>=21&&n<=57){const letter=consonants[n-21];return letter?letter+'a':c;}if(n in vowels)return vowels[n];if(n in marks)return marks[n];if(n>=102&&n<=111)return String(n-102);return c;}).join('').replace(/a(aa|ii|uu|ai|au|i|u|e|o)/g,'$1').replace(/a(?=\s|$)/g,'');}
export function enrichTrend(item){const headlines=(item.articles||[]).map(a=>a.title);const text=[item.title,...headlines].join(' ').toLowerCase();
 const rules=[['Politics',/election|minister|protest|munir|scindia|सिंधिया|തിരഞ്ഞെടുപ്പ്|चुनाव|నాయుడు|തിരഞ്ഞെട/, 'Explain the confirmed facts and timeline, with dates and named sources.'],['Cricket',/cricket|t20|ipl|asia cup|एशिया कप|scorecard/, 'Break down one match turning point using the scorecard and your own commentary.'],['Cinema',/cinema|actor|actress|movie|film|box office|ಚಿಕ್ಕಣ್ಣ/, 'Make a short profile or film explainer, separating reported facts from opinion.'],['Tech',/microsoft|apple|phone|samsung|software|technology|ai/, 'Explain what this topic means for everyday users, using one practical example.'],['Education',/ugc|exam|registration|student|net december/, 'Walk through the official notice and key dates. Check the application source before posting.'],['Weather',/weather|rain|cyclone|flood|storm/, 'Explain the forecast and practical precautions using the official bulletin.'],['Culture',/festival|dussehra|dasara|పండుగ/, 'Build a useful festival explainer or travel checklist from the linked reports.'],['Finance',/share price|bank|salary|stock|market/, 'Explain the numbers and context without turning it into investment advice.']];
 const rule=rules.find(([,rx])=>rx.test(text))||['News',null,'Compare the linked reports and explain the topic in plain language. Verify any claim before publishing.'];
 const labels={'పండుగ':'Panduga (festival)','सिंधिया':'Scindia','ಚಿಕ್ಕಣ್ಣ':'Chikkanna','మందాడి':'Mandadi','തിരഞ്ഞെടുപ്പ്':'Thiranjeduppu (election)','एशिया कप':'Asia Cup'};
 const english=headlines.find(h=>/^[\x00-\x7F]+$/.test(h));
 const label=/^[\x00-\x7F]+$/.test(item.title)?item.title:labels[item.title]||transliterate(item.title);
 return {...item,englishLabel:label,labelKind:label===item.title?'Original title':'Approximate transliteration',category:rule[0],videoAngle:rule[2],englishHeadline:english||null};}
