// Deterministic topic labels, not a translation or an AI claim.
const consonants={21:'k',22:'kh',23:'g',24:'gh',25:'ng',26:'ch',27:'chh',28:'j',29:'jh',30:'ny',31:'t',32:'th',33:'d',34:'dh',35:'n',36:'t',37:'th',38:'d',39:'dh',40:'n',42:'p',43:'ph',44:'b',45:'bh',46:'m',47:'y',48:'r',49:'r',50:'l',51:'l',52:'zh',53:'v',54:'sh',55:'sh',56:'s',57:'h'};
const scripts=[0x0900,0x0a00,0x0a80,0x0b00,0x0b80,0x0c00,0x0c80,0x0d00];
const vowels={5:'a',6:'aa',7:'i',8:'ii',9:'u',10:'uu',11:'ri',15:'e',16:'ai',19:'o',20:'au'};
const marks={62:'aa',63:'i',64:'ii',65:'u',66:'uu',67:'ri',70:'e',71:'e',72:'ai',74:'o',75:'o',76:'au',77:'',1:'n',2:'m',3:'h'};
export function transliterate(value){let out='';for(const c of value){const cp=c.codePointAt(0),base=scripts.find(b=>cp>=b&&cp<b+128);if(base===undefined){out+=c;continue;}const n=cp-base;if(n in consonants){out+=consonants[n]+'a';continue;}if(n in vowels){out+=vowels[n];continue;}if(n in marks){if(n>=62&&n<=77&&out.endsWith('a'))out=out.slice(0,-1);out+=marks[n];continue;}if(n>=102&&n<=111){out+=String(n-102);continue;}out+=c;}return out;}

export function enrichTrend(item){const headlines=(item.articles||[]).map(a=>a.title);const text=[item.title,...headlines].join(' ').toLowerCase();
 const rules=[['Politics',/pakistan air force|election|minister|protest|munir|scindia|सिंधिया|തിരഞ്ഞെടുപ്പ്|चुनाव|నాయుడు|തിരഞ്ഞെട/, 'Explain the confirmed facts and timeline, with dates and named sources.'],['Cricket',/cricket|t20|ipl|asia cup|एशिया कप|scorecard/, 'Break down one match turning point using the scorecard and your own commentary.'],['Cinema',/cinema|actor|actress|movie|film|box office|ಚಿಕ್ಕಣ್ಣ/, 'Make a short profile or film explainer, separating reported facts from opinion.'],['Finance',/share price|bank|salary|stock|market/, 'Explain the numbers and context without turning it into investment advice.'],['Tech',/microsoft|apple|phone|samsung|software|technology|ai/, 'Explain what this topic means for everyday users, using one practical example.'],['Education',/ugc|exam|registration|student|net december/, 'Walk through the official notice and key dates. Check the application source before posting.'],['Weather',/weather|rain|cyclone|flood|storm/, 'Explain the forecast and practical precautions using the official bulletin.'],['Culture',/festival|dussehra|dasara|పండుగ/, 'Build a useful festival explainer or travel checklist from the linked reports.'],['Finance',/share price|bank|salary|stock|market/, 'Explain the numbers and context without turning it into investment advice.']];
 const rule=rules.find(([,rx])=>rx.test(text))||['News',null,'Compare the linked reports and explain the topic in plain language. Verify any claim before publishing.'];
 const labels={'ಪರೀಕ್ಷೆ':'Parikshe (exam)','పండుగ':'Panduga (festival)','सिंधिया':'Scindia','ಚಿಕ್ಕಣ್ಣ':'Chikkanna','మందాడి':'Mandadi','തിരഞ്ഞെടുപ്പ്':'Thiranjeduppu (election)','एशिया कप':'Asia Cup'};
 const english=headlines.find(h=>/^[\x00-\x7F]+$/.test(h));
 const label=/^[\x00-\x7F]+$/.test(item.title)?item.title:labels[item.title]||transliterate(item.title);
 return {...item,englishLabel:label,labelKind:label===item.title?'Original title':'Approximate transliteration',category:rule[0],videoAngle:rule[2],englishHeadline:english||null};}
