import React,{useState} from 'react';
import {Plus,ArrowRight,Trash2,Download,X} from 'lucide-react';
const STAGES=['Idea','Scripting','Recording','Published'];
const COLORS={Idea:'#4B35E8',Scripting:'#B45309',Recording:'#7C3AED',Published:'#047857'};
const casing=s=>(s||'').replace(/\b(nfc|ugc|csa|t20|ipl|cisf|upi|tcs|kbc)\b/gi,x=>x.toUpperCase());
function Card({idea,onUpdateStatus,onDelete,onEdit,onOpen}){
 const [hook,setHook]=useState(idea.hookText||''),[editing,setEditing]=useState(false);
 return <article draggable onDragStart={e=>e.dataTransfer.setData('text/plain',idea.id)} className="bg-white rounded-2xl border border-line p-4 space-y-3 shadow-card text-sm"><span className="badge bg-surface text-brand capitalize">{idea.genre||'General'}</span><button className="block text-left w-full" onClick={()=>onOpen(idea)} aria-label={'Open full brief for '+casing(idea.topic)}><h3 className="font-extrabold text-base text-ink">{casing(idea.titleVariant||idea.topic)}</h3><p className="text-ink-2 mt-2">{idea.headline||idea.notes?.slice(0,170)||'Add your angle and notes.'}</p><span className="block text-brand font-bold mt-2">Open full brief</span></button><p className="text-ink-2">Saved {new Date(idea.savedAt).toLocaleDateString()}{idea.contextDate?' · Topic '+new Date(idea.contextDate).toLocaleDateString():''}{idea.searchVolume?' · '+idea.searchVolume+' searches':''}</p>{idea.sourceUrl&&<a href={idea.sourceUrl} target="_blank" rel="noopener noreferrer" className="block text-brand break-words">Read source{idea.sourcePublisher?' ('+idea.sourcePublisher+')':''}</a>}<div className="bg-surface rounded-xl p-3"><div className="flex justify-between gap-2"><strong className="text-ink-2">Hook</strong><button className="text-brand font-bold" onClick={()=>setEditing(!editing)}>{editing?'Cancel':'Edit hook'}</button></div>{editing?<div><label className="sr-only" htmlFor={'hook-'+idea.id}>Edit hook</label><textarea id={'hook-'+idea.id} className="w-full mt-2 p-2 border border-line rounded-lg text-ink" rows={3} maxLength={2000} value={hook} onChange={e=>setHook(e.target.value)}/><button className="text-brand font-bold mt-2" onClick={async()=>{if(await onEdit(idea.id,{hookText:hook})!==false)setEditing(false);}}>Save hook</button></div>:<p className="text-ink-2 mt-2">{idea.hookText||'Write your opening hook.'}</p>}</div><div className="flex justify-between items-center gap-2"><select aria-label={'Stage for '+casing(idea.topic)} value={idea.status||'Idea'} onChange={e=>onUpdateStatus(idea.id,e.target.value)} className="text-sm rounded-lg px-2 py-1.5 border border-line bg-white text-ink-2">{STAGES.map(s=><option key={s}>{s}</option>)}</select><button aria-label={'Delete '+casing(idea.topic)} onClick={()=>onDelete(idea.id)} className="p-2 rounded-lg text-red-700 bg-red-50"><Trash2 className="w-4 h-4"/></button></div></article>;
}
export default function CreatorBacklog({savedIdeas,onUpdateStatus,onDeleteIdea,onAddNewIdea,onEditIdea,onSwitchToFeed}){
 const [stage,setStage]=useState('Idea'),[showAdd,setShowAdd]=useState(false),[topic,setTopic]=useState(''),[notes,setNotes]=useState(''),[opened,setOpened]=useState(null),[exportMessage,setExportMessage]=useState('');
 const exportBoard=()=>{try{const md=['# TrendPulse Idea board','Saved in this browser only. Exported '+new Date().toISOString(),...savedIdeas.map(i=>'\n## '+casing(i.titleVariant||i.topic)+'\nStage: '+(i.status||'Idea')+'\nSaved: '+i.savedAt+(i.contextDate?'\nTopic date: '+i.contextDate:'')+(i.searchVolume?'\nSearch volume: '+i.searchVolume:'')+'\n\nHook: '+(i.hookText||'')+'\n\n'+(i.notes||'')+(i.sourceUrl?'\n\nSource: '+i.sourceUrl:''))].join('\n');const url=URL.createObjectURL(new Blob([md],{type:'text/markdown;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='trendpulse-idea-board.md';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);setExportMessage('Markdown export downloaded. Keep a copy outside this browser.');}catch{setExportMessage('Export failed. Please try again.');}};
 const columns=STAGES.filter(s=>savedIdeas.some(i=>(i.status||'Idea')===s));
 const renderColumn=s=>{const items=savedIdeas.filter(i=>(i.status||'Idea')===s);return <section key={s} onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();const id=e.dataTransfer.getData('text/plain');if(savedIdeas.some(i=>i.id===id))onUpdateStatus(id,s);}} className="space-y-3"><h3 className="flex justify-between items-center font-bold text-ink"><span className="flex gap-2 items-center"><span className="w-2.5 h-2.5 rounded-full" style={{background:COLORS[s]}}/>{s}</span><span>{items.length}</span></h3>{items.length?items.map(i=><Card key={i.id} idea={i} onUpdateStatus={onUpdateStatus} onDelete={onDeleteIdea} onEdit={onEditIdea} onOpen={setOpened}/>):<p className="text-sm text-ink-2 bg-white rounded-xl p-4">No ideas in {s} yet. Move an idea here using its stage menu.</p>}</section>};
 return <div className="space-y-6"><div className="card p-6"><span className="section-label">Your saved ideas</span><h2 className="text-2xl font-extrabold text-ink mt-2">Idea board</h2><p className="text-sm text-ink-2 mt-2">Saved in this browser only. Clearing site data removes these ideas. Export a copy to keep them.</p><div className="flex flex-wrap gap-3 mt-4"><button onClick={()=>setShowAdd(true)} className="btn-brand"><Plus className="w-4 h-4"/>Add idea</button><button onClick={onSwitchToFeed} className="btn-outline">Today's trends<ArrowRight className="w-4 h-4"/></button><button disabled={!savedIdeas.length} onClick={exportBoard} className="btn-outline"><Download className="w-4 h-4"/>Export Markdown</button></div>{exportMessage&&<p role="status" className="text-sm mt-3 text-ink-2">{exportMessage}</p>}</div>{!savedIdeas.length?<div className="card p-8 text-center"><h3 className="text-xl font-bold text-ink">Save a trend to start your board</h3><p className="text-sm text-ink-2 mt-3">Keep the topic, sources and your hook together.</p><button className="btn-brand mt-5" onClick={onSwitchToFeed}>Today's trends</button></div>:<><div role="tablist" aria-label="Idea stages" className="md:hidden flex flex-wrap gap-2">{STAGES.map(s=><button key={s} role="tab" aria-selected={stage===s} className={stage===s?'btn-brand':'btn-outline'} onClick={()=>setStage(s)}>{s} ({savedIdeas.filter(i=>(i.status||'Idea')===s).length})</button>)}</div><div className="md:hidden" role="tabpanel">{renderColumn(stage)}</div><div className="hidden md:grid gap-5" style={{gridTemplateColumns:'repeat('+Math.min(columns.length,4)+', minmax(0,1fr))'}}>{columns.map(renderColumn)}</div><div className="hidden md:flex flex-wrap gap-3 text-sm text-ink-2">{STAGES.filter(s=>!columns.includes(s)).map(s=><div key={s} onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();const id=e.dataTransfer.getData('text/plain');if(savedIdeas.some(i=>i.id===id))onUpdateStatus(id,s);}} className="rounded-lg border border-line p-3">{s}: 0 · Drop here or use a card's stage menu</div>)}</div></>}
 {opened&&<div className="fixed inset-0 z-50 bg-black/50 p-4 flex items-center justify-center" onClick={e=>{if(e.target===e.currentTarget)setOpened(null);}}><section role="dialog" aria-modal="true" aria-label="Saved idea brief" className="bg-white rounded-2xl p-6 max-w-2xl w-full max-h-[85vh] overflow-y-auto text-sm"><div className="flex justify-between gap-4"><h3 className="text-xl font-extrabold text-ink">{casing(opened.titleVariant||opened.topic)}</h3><button aria-label="Close saved brief" onClick={()=>setOpened(null)}><X/></button></div><p className="text-ink-2 mt-4">Saved {new Date(opened.savedAt).toLocaleString()}{opened.searchVolume?' · '+opened.searchVolume+' searches':''}</p><h4 className="font-bold mt-5">Your hook</h4><p className="text-ink-2 mt-2 whitespace-pre-wrap">{opened.hookText||'No hook added yet.'}</p><h4 className="font-bold mt-5">Full brief and context</h4><p className="text-ink-2 mt-2 whitespace-pre-wrap">{opened.fullBrief||opened.notes||'No notes added yet.'}</p>{opened.sourceUrl&&<a className="text-brand mt-5 block break-words" href={opened.sourceUrl} target="_blank" rel="noopener noreferrer">Read original source</a>}<button className="btn-outline mt-5" onClick={()=>setOpened(null)}>Close</button></section></div>}
 {showAdd&&<div className="fixed inset-0 z-50 bg-black/50 p-4 flex items-center justify-center"><form role="dialog" aria-modal="true" aria-label="Add idea" className="bg-white rounded-2xl p-6 max-w-md w-full space-y-4" onSubmit={async e=>{e.preventDefault();if(await onAddNewIdea({topic:topic.trim(),titleVariant:topic.trim(),genre:'general',hookText:'',notes,targetPlatform:'youtube'})!==false){setShowAdd(false);setTopic('');setNotes('');}}}><h3 className="text-xl font-bold">Add idea</h3><label className="text-sm block">Topic<input required maxLength={250} value={topic} onChange={e=>setTopic(e.target.value)} className="w-full p-3 border border-line rounded-xl mt-2"/></label><label className="text-sm block">Notes<textarea maxLength={10000} rows={4} value={notes} onChange={e=>setNotes(e.target.value)} className="w-full p-3 border border-line rounded-xl mt-2"/></label><div className="flex gap-3"><button className="btn-brand">Save to Idea board</button><button type="button" className="btn-outline" onClick={()=>setShowAdd(false)}>Cancel</button></div></form></div>}</div>;
}
